openapi: 3.0.3
info:
  title: Velaris API
  version: "1.0.0"
  description: API dla aplikacji Velaris – śledzenie inwestycji i kolekcji (MVP)
servers:
  - url: https://api.velaris.app/api/v1
    description: Production server
  - url: http://localhost:8080/api/v1
    description: Local dev server

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      $ref: './components/schemas/user.yaml'

    JwtResponse:
      $ref: './components/schemas/jwt-response.yaml'

    RegisterRequest:
      $ref: './components/schemas/register-request.yaml'

    LoginRequest:
      $ref: './components/schemas/login-request.yaml'

    Asset:
      $ref: './components/schemas/asset.yaml'

    Note:
      $ref: './components/schemas/note.yaml'

    StatsOverview:
      $ref: './components/schemas/stats-overview.yaml'

    StatsCategoryItem:
      $ref: './components/schemas/stats-category-item.yaml'

    StatsTrendItem:
      $ref: './components/schemas/stats-trend-item.yaml'

    RecentActivitiesItem:
      $ref: './components/schemas/recent-activities-item.yaml'

    StatsTagItem:
      $ref: './components/schemas/stats-tag-item.yaml'

    StatsTrendDiffItem:
      $ref: './components/schemas/stats-trend-diff-item.yaml'

    StatsTopMoversItem:
      $ref: './components/schemas/stats-top-movers-item.yaml'

    StatsCategoryTrendItem:
      $ref: './components/schemas/stats-category-trend-item.yaml'

paths:
  /auth/register:
    $ref: './paths/auth/register.yaml'

  /auth/login:
    $ref: './paths/auth/login.yaml'

  /assets:
    $ref: './paths/assets/assets.yaml'

  /assets/{id}:
    $ref: './paths/assets/asset-by-id.yaml'

  /assets/activities:
    $ref: './paths/assets/assets-activities.yaml'

  /stats/overview:
    $ref: './paths/stats/overview.yaml'

  /stats/category:
    $ref: './paths/stats/category.yaml'

  /stats/trend:
    $ref: './paths/stats/trend.yaml'

  /stats/tag:
    $ref: './paths/stats/tag.yaml'

  /stats/trend-diff:
    $ref: './paths/stats/trend-diff.yaml'

  /stats/top-movers:
    $ref: './paths/stats/top-movers.yaml'

  /stats/category-trend:
    $ref: './paths/stats/category-trend.yaml'