name: Gradle Release

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git user
        run: |
          git config --global user.email "ci@calendar-api.com"
          git config --global user.name "Calendar API CI"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Release or Snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
            echo "🔥 Performing release"
            ./gradlew release publish
          else
            echo "📦 Performing snapshot publish only"
            ./gradlew publish
          fi
